# Generated by Django 3.2.7 on 2023-08-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('News_title', models.CharField(max_length=200, verbose_name='name')),
                ('News_content', models.CharField(max_length=500, verbose_name='content')),
                ('News_date', models.DateField(auto_now_add=True)),
                ('News_Picture', models.ImageField(null=True, upload_to='images/news/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('Sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sub_date', models.CharField(max_length=100, null=True, verbose_name='sub_date')),
                ('Sub_end', models.CharField(max_length=200, null=True, verbose_name='end_date')),
                ('Sub_trans_id', models.CharField(max_length=16, null=True, verbose_name='sub_trans_id')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=200, verbose_name='name')),
                ('User_email', models.CharField(max_length=100, unique=True, verbose_name='email')),
                ('User_address', models.CharField(max_length=200, verbose_name='address')),
                ('User_phone', models.CharField(max_length=12, verbose_name='phone')),
                ('User_ARU', models.CharField(max_length=100, verbose_name='ARU')),
                ('User_nomin', models.CharField(max_length=100, verbose_name='nomin_name')),
                ('User_join', models.CharField(max_length=100, verbose_name='join_date')),
                ('User_retire', models.CharField(max_length=100, verbose_name='retire_date')),
                ('User_age', models.IntegerField(verbose_name='age')),
                ('User_birth', models.CharField(max_length=100, verbose_name='birth_date')),
                ('User_position', models.CharField(max_length=100, verbose_name='retired_post')),
                ('User_permitted', models.BooleanField(default=False)),
                ('Log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.login')),
                ('User_Sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('Admin_name', models.CharField(max_length=200, verbose_name='name')),
                ('Admin_email', models.CharField(max_length=100, unique=True, verbose_name='email')),
                ('Admin_address', models.CharField(max_length=200, verbose_name='address')),
                ('Admin_phone', models.CharField(max_length=12, verbose_name='phone')),
                ('Admin_Area', models.CharField(max_length=100, verbose_name='ARU')),
                ('Admin_position', models.CharField(max_length=100, verbose_name='working position')),
                ('Admin_permitted', models.BooleanField(default=False)),
                ('Log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.login')),
            ],
        ),
    ]
