# Generated by Django 3.2.7 on 2023-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_user_user_permitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='News_content',
            field=models.CharField(max_length=2000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='News_title',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
    ]
