# Generated by Django 3.2.7 on 2023-08-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20230813_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Admin_Picture',
            field=models.ImageField(null=True, upload_to='images/admins/'),
        ),
    ]
